import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import BuildOutlinedIcon from '@mui/icons-material/BuildOutlined';
import AssignmentTurnedInOutlinedIcon from '@mui/icons-material/AssignmentTurnedInOutlined';
import { downloadCsv, http } from '../../api/http';

type Machine = { id: string; code: string; name: string; currentMeter: string; status: string; maintenancePlans: { id: string; nextDueMeter: string; warningHours: string; active: boolean }[] };
type Platform = { id: string; name: string; project: { name: string } };
type Assignment = { id: string; workDate: string; operator?: string; meterStart: string; meterEnd: string; hoursWorked: string; machine: Machine; platformId: string };
type Repair = { id: string; repairedAt: string; meterReading: string; downtimeHours: string; notes?: string; machine: Machine };
type MaintenanceRecord = { id: string; performedAt: string; meterReading: string; operator: string; nextDueMeter?: string; notes?: string; machine: Machine };
type DialogKind = 'machine' | 'assignment' | 'maintenance' | 'service' | 'repair' | null;
const today = new Date().toISOString().slice(0, 10);
const empty = { code: '', name: '', currentMeter: '0', machineId: '', platformId: '', workDate: today, operator: '', meterStart: '', meterEnd: '', hoursWorked: '', intervalHours: '', nextDueMeter: '', warningHours: '50', meterReading: '', repairedAt: today, downtimeHours: '0', notes: '' };
function dateLabel(value: string) { return new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium' }).format(new Date(value)); }

export function EquipmentPage() {
  const queryClient = useQueryClient();
  const machines = useQuery({ queryKey: ['machines'], queryFn: async () => (await http.get<Machine[]>('/machines')).data, retry: false });
  const platforms = useQuery({ queryKey: ['platforms'], queryFn: async () => (await http.get<Platform[]>('/platforms')).data, retry: false });
  const assignments = useQuery({ queryKey: ['assignments'], queryFn: async () => (await http.get<Assignment[]>('/machine-assignments')).data, retry: false });
  const repairs = useQuery({ queryKey: ['repairs'], queryFn: async () => (await http.get<Repair[]>('/repairs')).data, retry: false });
  const maintenanceRecords = useQuery({ queryKey: ['maintenance-records'], queryFn: async () => (await http.get<MaintenanceRecord[]>('/maintenance-records')).data, retry: false });
  const [dialog, setDialog] = useState<DialogKind>(null); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const platformNames = useMemo(() => new Map((platforms.data ?? []).map((platform) => [platform.id, `${platform.project.name} · ${platform.name}`])), [platforms.data]);
  const open = (kind: DialogKind) => { const firstMachine = machines.data?.[0]?.id ?? ''; setForm({ ...empty, machineId: firstMachine, platformId: platforms.data?.[0]?.id ?? '' }); setDialog(kind); setError(''); setMessage(''); };
  const save = async () => {
    const config = dialog === 'machine' ? { url: '/machines', body: { code: form.code, name: form.name, currentMeter: Number(form.currentMeter) } }
      : dialog === 'assignment' ? { url: '/machine-assignments', body: { machineId: form.machineId, platformId: form.platformId, workDate: form.workDate, operator: form.operator || undefined, meterStart: Number(form.meterStart), meterEnd: Number(form.meterEnd), hoursWorked: Number(form.hoursWorked) } }
      : dialog === 'maintenance' ? { url: '/maintenance-plans', body: { machineId: form.machineId, intervalHours: Number(form.intervalHours), nextDueMeter: Number(form.nextDueMeter), warningHours: Number(form.warningHours) } }
      : dialog === 'service' ? { url: '/maintenance-records', body: { machineId: form.machineId, performedAt: form.repairedAt, meterReading: Number(form.meterReading), operator: form.operator, notes: form.notes || undefined } }
      : { url: '/repairs', body: { machineId: form.machineId, meterReading: Number(form.meterReading), repairedAt: form.repairedAt, operator: form.operator || undefined, downtimeHours: Number(form.downtimeHours), notes: form.notes || undefined } };
    setSaving(true); setError('');
    try { await http.post(config.url, config.body); await Promise.all(['machines', 'assignments', 'repairs', 'maintenance-records', 'dashboard'].map((key) => queryClient.invalidateQueries({ queryKey: [key] }))); setMessage(dialog === 'repair' ? 'Reparación registrada; la unidad quedó disponible.' : dialog === 'service' ? 'Mantenimiento ejecutado y próximo servicio recalculado.' : 'Registro guardado correctamente.'); setDialog(null); }
    catch (reason) { const apiMessage = (reason as { response?: { data?: { message?: string | string[] } } }).response?.data?.message; setError(Array.isArray(apiMessage) ? apiMessage.join('. ') : apiMessage ?? 'No fue posible guardar. Revisa los campos y tus permisos.'); }
    finally { setSaving(false); }
  };
  return <Stack spacing={2.5}>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h3" sx={{ fontSize: { xs: 34, sm: 46 } }}>Maquinaria</Typography><Typography color="text.secondary" sx={{ mt: .6 }}>Unidades, horómetros, asignaciones, mantenimiento y reparaciones.</Typography></Box><Stack direction="row" gap={1}><Button variant="outlined" onClick={() => downloadCsv('/exports/equipment.csv', 'maquinaria.csv')}>Exportar CSV</Button><Button variant="contained" color="secondary" startIcon={<AddIcon />} onClick={() => open('machine')}>Registrar unidad</Button></Stack></Stack>
    {message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}
    <Box className="page-grid"><Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Unidades</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Unidad</TableCell><TableCell>Estado</TableCell><TableCell align="right">Horómetro</TableCell><TableCell>Servicio</TableCell></TableRow></TableHead><TableBody>{(machines.data ?? []).map((machine) => <TableRow key={machine.id}><TableCell>{machine.code} · {machine.name}</TableCell><TableCell><Chip size="small" label={machine.status} color={machine.status === 'WORKING' ? 'warning' : machine.status === 'AVAILABLE' ? 'success' : 'default'} /></TableCell><TableCell align="right">{machine.currentMeter}</TableCell><TableCell>{serviceLabel(machine)}</TableCell></TableRow>)}{!machines.data?.length && <TableRow><TableCell colSpan={4} align="center">Aún no hay maquinaria registrada.</TableCell></TableRow>}</TableBody></Table></Paper>
      <Paper sx={{ p: 2.5 }}><Typography variant="h6">Operación de equipo</Typography><Typography color="text.secondary" variant="body2" sx={{ mt: .6, mb: 2 }}>La asignación actualiza el horómetro y marca la unidad como trabajando.</Typography><Stack spacing={1}><Button variant="outlined" startIcon={<AssignmentTurnedInOutlinedIcon />} disabled={!machines.data?.length || !platforms.data?.length} onClick={() => open('assignment')}>Asignar unidad</Button><Button variant="outlined" startIcon={<BuildOutlinedIcon />} disabled={!machines.data?.length} onClick={() => open('maintenance')}>Plan de mantenimiento</Button><Button variant="contained" disabled={!machines.data?.length} onClick={() => open('service')}>Registrar mantenimiento ejecutado</Button><Button variant="outlined" disabled={!machines.data?.length} onClick={() => open('repair')}>Registrar reparación</Button></Stack></Paper></Box>
    <Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Asignaciones recientes</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Unidad</TableCell><TableCell>Plataforma</TableCell><TableCell>Operador</TableCell><TableCell align="right">Horas</TableCell></TableRow></TableHead><TableBody>{(assignments.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{dateLabel(item.workDate)}</TableCell><TableCell>{item.machine.code}</TableCell><TableCell>{platformNames.get(item.platformId) ?? '—'}</TableCell><TableCell>{item.operator ?? '—'}</TableCell><TableCell align="right">{item.hoursWorked}</TableCell></TableRow>)}{!assignments.data?.length && <TableRow><TableCell colSpan={5} align="center">Sin asignaciones registradas.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Reparaciones</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Unidad</TableCell><TableCell>Horómetro</TableCell><TableCell align="right">Tiempo detenido</TableCell></TableRow></TableHead><TableBody>{(repairs.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{dateLabel(item.repairedAt)}</TableCell><TableCell>{item.machine.code} · {item.machine.name}</TableCell><TableCell>{item.meterReading}</TableCell><TableCell align="right">{item.downtimeHours} h</TableCell></TableRow>)}{!repairs.data?.length && <TableRow><TableCell colSpan={4} align="center">Sin reparaciones registradas.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Mantenimientos ejecutados</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Fecha</TableCell><TableCell>Unidad</TableCell><TableCell>Responsable</TableCell><TableCell>Horómetro</TableCell><TableCell>Próximo servicio</TableCell></TableRow></TableHead><TableBody>{(maintenanceRecords.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{dateLabel(item.performedAt)}</TableCell><TableCell>{item.machine.code} · {item.machine.name}</TableCell><TableCell>{item.operator}</TableCell><TableCell>{item.meterReading}</TableCell><TableCell>{item.nextDueMeter ?? 'Sin plan'}</TableCell></TableRow>)}{!maintenanceRecords.data?.length && <TableRow><TableCell colSpan={5} align="center">Sin mantenimientos ejecutados.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Dialog open={Boolean(dialog)} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>{dialog === 'machine' ? 'Registrar unidad' : dialog === 'assignment' ? 'Asignar unidad' : dialog === 'maintenance' ? 'Plan de mantenimiento' : dialog === 'service' ? 'Registrar mantenimiento ejecutado' : 'Registrar reparación'}</DialogTitle><DialogContent><EquipmentForm kind={dialog} form={form} setForm={setForm} machines={machines.data ?? []} platforms={platforms.data ?? []} /></DialogContent><DialogActions><Button onClick={() => setDialog(null)}>Cancelar</Button><Button variant="contained" color="secondary" disabled={saving} onClick={save}>{saving ? 'Guardando…' : 'Guardar'}</Button></DialogActions></Dialog>
  </Stack>;
}
function serviceLabel(machine: Machine) { const plan = machine.maintenancePlans[0]; if (!plan) return 'Sin plan'; return Number(machine.currentMeter) >= Number(plan.nextDueMeter) ? `Vencido: ${plan.nextDueMeter}` : Number(machine.currentMeter) >= Number(plan.nextDueMeter) - Number(plan.warningHours) ? `Próximo: ${plan.nextDueMeter}` : `Programado: ${plan.nextDueMeter}`; }
function EquipmentForm({ kind, form, setForm, machines, platforms }: { kind: DialogKind; form: typeof empty; setForm: (value: typeof empty) => void; machines: Machine[]; platforms: Platform[] }) { const set = (name: keyof typeof empty, value: string) => setForm({ ...form, [name]: value }); return <Stack spacing={2} sx={{ pt: 1 }}>
  {kind === 'machine' && <><TextField label="Número económico" value={form.code} onChange={(event) => set('code', event.target.value)} required /><TextField label="Nombre o descripción" value={form.name} onChange={(event) => set('name', event.target.value)} required /><TextField label="Horómetro inicial" type="number" value={form.currentMeter} onChange={(event) => set('currentMeter', event.target.value)} inputProps={{ min: 0 }} /></>}
  {kind !== 'machine' && <TextField select label="Unidad" value={form.machineId} onChange={(event) => set('machineId', event.target.value)} required>{machines.map((machine) => <MenuItem key={machine.id} value={machine.id}>{machine.code} · {machine.name}</MenuItem>)}</TextField>}
  {kind === 'assignment' && <><TextField select label="Plataforma" value={form.platformId} onChange={(event) => set('platformId', event.target.value)} required>{platforms.map((platform) => <MenuItem key={platform.id} value={platform.id}>{platform.project.name} · {platform.name}</MenuItem>)}</TextField><TextField label="Fecha de trabajo" type="date" value={form.workDate} onChange={(event) => set('workDate', event.target.value)} InputLabelProps={{ shrink: true }} required /><TextField label="Operador" value={form.operator} onChange={(event) => set('operator', event.target.value)} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="Horómetro inicial" type="number" value={form.meterStart} onChange={(event) => set('meterStart', event.target.value)} required /><TextField fullWidth label="Horómetro final" type="number" value={form.meterEnd} onChange={(event) => set('meterEnd', event.target.value)} required /><TextField fullWidth label="Horas trabajadas" type="number" value={form.hoursWorked} onChange={(event) => set('hoursWorked', event.target.value)} required /></Stack></>}
  {kind === 'maintenance' && <><TextField label="Intervalo de servicio (h)" type="number" value={form.intervalHours} onChange={(event) => set('intervalHours', event.target.value)} required /><TextField label="Próximo servicio (horómetro)" type="number" value={form.nextDueMeter} onChange={(event) => set('nextDueMeter', event.target.value)} required /><TextField label="Avisar antes (h)" type="number" value={form.warningHours} onChange={(event) => set('warningHours', event.target.value)} required /></>}
  {kind === 'service' && <><TextField label="Fecha de mantenimiento" type="date" value={form.repairedAt} onChange={(event) => set('repairedAt', event.target.value)} InputLabelProps={{ shrink: true }} required /><TextField label="Horómetro" type="number" value={form.meterReading} onChange={(event) => set('meterReading', event.target.value)} required /><TextField label="Responsable" value={form.operator} onChange={(event) => set('operator', event.target.value)} required /><TextField label="Trabajo realizado" value={form.notes} onChange={(event) => set('notes', event.target.value)} multiline minRows={3} /></>}
  {kind === 'repair' && <><TextField label="Fecha de reparación" type="date" value={form.repairedAt} onChange={(event) => set('repairedAt', event.target.value)} InputLabelProps={{ shrink: true }} required /><TextField label="Horómetro" type="number" value={form.meterReading} onChange={(event) => set('meterReading', event.target.value)} required /><TextField label="Operador" value={form.operator} onChange={(event) => set('operator', event.target.value)} /><TextField label="Tiempo detenido (h)" type="number" value={form.downtimeHours} onChange={(event) => set('downtimeHours', event.target.value)} inputProps={{ min: 0 }} /><TextField label="Notas" value={form.notes} onChange={(event) => set('notes', event.target.value)} multiline minRows={2} /></>}
  </Stack>; }
