import { useState } from 'react';
import { Box, Button, CircularProgress, Paper, Stack, TextField, Typography } from '@mui/material';
import ConstructionOutlinedIcon from '@mui/icons-material/ConstructionOutlined';
import { login } from '../../api/http';
export function LoginPage() {
  const [email, setEmail] = useState('admin@trojes.local'); const [password, setPassword] = useState('Admin123!'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const session = await login(email, password); localStorage.setItem('tdm_access_token', session.accessToken); localStorage.setItem('tdm_refresh_token', session.refreshToken); localStorage.setItem('tdm_user', JSON.stringify(session.user)); window.location.assign('/'); } catch { setError('No fue posible iniciar sesión. Verifica tus credenciales.'); } finally { setLoading(false); } };
  return <Box sx={{ minHeight: '100vh', display: 'grid', placeItems: 'center', p: 3, bgcolor: '#f4f8f5' }}><Paper sx={{ width: '100%', maxWidth: 430, p: { xs: 3, sm: 5 } }}><Stack spacing={3} component="form" onSubmit={submit}><Stack direction="row" spacing={1.5} alignItems="center"><Box sx={{ display: 'grid', placeItems: 'center', bgcolor: 'primary.main', color: '#fff', width: 44, height: 44, borderRadius: 2 }}><ConstructionOutlinedIcon /></Box><Typography variant="h5">Trojes de Marañón</Typography></Stack><Box><Typography variant="h4" sx={{ fontWeight: 750 }}>Entrar a obra</Typography><Typography color="text.secondary">Control operativo para supervisores.</Typography></Box><TextField label="Correo" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /><TextField label="Contraseña" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" helperText={error || 'Usuario inicial: admin@trojes.local'} error={Boolean(error)} /><Button type="submit" size="large" variant="contained" color="secondary" disabled={loading}>{loading ? <CircularProgress size={22} color="inherit" /> : 'Iniciar sesión'}</Button></Stack></Paper></Box>;
}
