import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsEmail, IsEnum, IsIn, IsNumber, IsOptional, IsString, Max, Min, MinLength } from 'class-validator';
import { DocumentStatus, MachineStatus, MovementType, ProjectStatus, UserRole, WarehouseKind } from '@prisma/client';
export class MaterialDto { @IsString() code!: string; @IsString() name!: string; @IsString() unit!: string; @Type(() => Number) @IsNumber() @Min(0) minimumStock!: number; }
export class WarehouseDto { @IsString() name!: string; @IsEnum(WarehouseKind) kind!: WarehouseKind; @IsOptional() @IsString() platformId?: string; }
export class ProjectDto { @IsString() name!: string; @IsOptional() @IsString() location?: string; @IsOptional() @IsEnum(ProjectStatus) status?: ProjectStatus; @IsOptional() @Type(() => Number) @IsNumber() varianceThreshold?: number; }
export class PlatformDto { @IsString() projectId!: string; @IsString() name!: string; @IsOptional() @IsString() location?: string; }
export class ActivityDto { @IsString() platformId!: string; @IsString() name!: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) @Max(100) progress?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) squareMeters?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) cubicMeters?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) trips?: number; @IsOptional() @IsString() notes?: string; @IsOptional() @IsArray() @IsString({ each: true }) pendingItems?: string[]; @IsOptional() @IsArray() @IsString({ each: true }) photoPaths?: string[]; }
export class UpdateActivityDto { @IsOptional() @IsString() name?: string; @IsOptional() @IsEnum(ProjectStatus) status?: ProjectStatus; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) @Max(100) progress?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) squareMeters?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) cubicMeters?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) trips?: number; @IsOptional() @IsString() notes?: string; @IsOptional() @IsArray() @IsString({ each: true }) pendingItems?: string[]; @IsOptional() @IsArray() @IsString({ each: true }) photoPaths?: string[]; }
export class EstimateDto { @IsString() platformId!: string; @IsOptional() @IsString() activityId?: string; @IsString() materialId!: string; @Type(() => Number) @IsNumber() @Min(0) quantity!: number; @IsOptional() @Type(() => Number) @IsNumber() threshold?: number; }
export class MovementDto { @IsEnum(MovementType) type!: MovementType; @IsString() materialId!: string; @IsString() warehouseId!: string; @IsOptional() @IsString() destinationWarehouseId?: string; @IsOptional() @IsString() platformId?: string; @IsOptional() @IsString() activityId?: string; @Type(() => Number) @IsNumber() quantity!: number; @IsOptional() @IsString() supplier?: string; @IsOptional() @IsString() remision?: string; @IsOptional() @IsString() responsible?: string; @IsOptional() @IsString() observation?: string; @IsOptional() @IsString() photoPath?: string; @IsOptional() @IsBoolean() approvalRequired?: boolean; @IsOptional() @IsString() occurredAt?: string; }
export class MachineDto { @IsString() code!: string; @IsString() name!: string; @IsOptional() @IsString() meterKind?: string; @IsOptional() @Type(() => Number) @IsNumber() currentMeter?: number; @IsOptional() @IsEnum(MachineStatus) status?: MachineStatus; @IsOptional() @Type(() => Number) @IsNumber() fuelTarget?: number; }
export class AssignmentDto { @IsString() machineId!: string; @IsString() platformId!: string; @IsString() workDate!: string; @IsOptional() @IsString() operator?: string; @Type(() => Number) @IsNumber() meterStart!: number; @Type(() => Number) @IsNumber() meterEnd!: number; @Type(() => Number) @IsNumber() @Min(0) hoursWorked!: number; }
export class FuelDto { @IsString() machineId!: string; @IsString() sourceWarehouseId!: string; @IsString() platformId!: string; @Type(() => Number) @IsNumber() @Min(0.001) liters!: number; @IsOptional() @Type(() => Number) @IsNumber() meterReading?: number; @IsString() operator!: string; @IsOptional() @IsString() loadedAt?: string; }
export class MaintenanceDto { @IsString() machineId!: string; @Type(() => Number) @IsNumber() intervalHours!: number; @Type(() => Number) @IsNumber() nextDueMeter!: number; @IsOptional() @Type(() => Number) @IsNumber() warningHours?: number; }
export class MaintenanceRecordDto { @IsString() machineId!: string; @IsOptional() @IsString() maintenancePlanId?: string; @IsString() performedAt!: string; @Type(() => Number) @IsNumber() @Min(0) meterReading!: number; @IsString() operator!: string; @IsOptional() @IsString() notes?: string; }
export class RepairDto { @IsString() machineId!: string; @Type(() => Number) @IsNumber() meterReading!: number; @IsString() repairedAt!: string; @IsOptional() @IsString() operator?: string; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) downtimeHours?: number; @IsOptional() @IsString() notes?: string; }
export class ReportDto { @IsString() platformId!: string; @IsString() reportDate!: string; @IsOptional() @Type(() => Number) @IsNumber() progress?: number; @IsOptional() @IsString() weather?: string; @IsOptional() @IsArray() @IsString({ each: true }) incidents?: string[]; @IsOptional() personnel?: object; @IsOptional() materials?: object; @IsOptional() machinery?: object; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) fuelLiters?: number; @IsOptional() @Type(() => Number) @IsNumber() @Min(0) overtimeHours?: number; @IsOptional() @IsArray() @IsString({ each: true }) pendingItems?: string[]; @IsOptional() @IsArray() @IsString({ each: true }) photoPaths?: string[]; @IsOptional() @IsString() notes?: string; }
export class CreateUserDto { @IsEmail() email!: string; @IsString() name!: string; @IsString() @MinLength(8) password!: string; @IsEnum(UserRole) role!: UserRole; }
export class UpdateUserDto { @IsOptional() @IsString() name?: string; @IsOptional() @IsString() @MinLength(8) password?: string; @IsOptional() @IsEnum(UserRole) role?: UserRole; @IsOptional() @IsBoolean() active?: boolean; }
export class SetActiveDto { @IsBoolean() active!: boolean; }
export class MachineStatusDto { @IsEnum(MachineStatus) status!: MachineStatus; }
export class StatusDto { @IsEnum(DocumentStatus) status!: DocumentStatus; }
export class PermissionGrantDto { @IsEnum(UserRole) role!: UserRole; @IsString() @IsIn(['INVENTORY_CAPTURE', 'INVENTORY_APPROVE', 'INVENTORY_CANCEL', 'REPORT_CAPTURE', 'REPORT_PUBLISH', 'REPORT_APPROVE', 'EQUIPMENT_CAPTURE']) permission!: string; @IsBoolean() allowed!: boolean; }
