import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { http } from '../../api/http';

type Material = { id: string; code: string; name: string; unit: string; minimumStock: string; active: boolean };
type Warehouse = { id: string; name: string; kind: string; active: boolean };
type User = { id: string; name: string; email: string; role: string; active: boolean };
type Permission = { role: string; permission: string; allowed: boolean };
type DialogKind = 'material' | 'warehouse' | 'user' | null;
const roles = ['ADMIN', 'APPROVER', 'SUPERVISOR', 'WAREHOUSE', 'EQUIPMENT', 'VIEWER'];
const roleLabel = (role: string) => ({ ADMIN: 'Administrador', APPROVER: 'Aprobador', SUPERVISOR: 'Supervisor', WAREHOUSE: 'Almacén', EQUIPMENT: 'Maquinaria', VIEWER: 'Consulta' }[role] ?? role);
const permissionLabel = (permission: string) => ({ INVENTORY_CAPTURE: 'Capturar inventario', INVENTORY_APPROVE: 'Autorizar salida sin stock', INVENTORY_CANCEL: 'Cancelar y revertir', REPORT_CAPTURE: 'Capturar reporte', REPORT_PUBLISH: 'Publicar reporte', REPORT_APPROVE: 'Aprobar reporte', EQUIPMENT_CAPTURE: 'Capturar maquinaria y diésel' }[permission] ?? permission);
const warehouseKinds = ['CONTAINER', 'OPEN_AREA', 'FUEL_TANK'];
const empty = { code: '', name: '', unit: '', minimumStock: '0', kind: 'CONTAINER', email: '', password: '', role: 'SUPERVISOR' };

export function AdminPage() {
  const queryClient = useQueryClient();
  const materials = useQuery({ queryKey: ['admin-materials'], queryFn: async () => (await http.get<Material[]>('/materials?includeInactive=true')).data, retry: false });
  const warehouses = useQuery({ queryKey: ['admin-warehouses'], queryFn: async () => (await http.get<Warehouse[]>('/warehouses?includeInactive=true')).data, retry: false });
  const users = useQuery({ queryKey: ['users'], queryFn: async () => (await http.get<User[]>('/users')).data, retry: false });
  const permissions = useQuery({ queryKey: ['permissions'], queryFn: async () => (await http.get<Permission[]>('/permissions')).data, retry: false });
  const [dialog, setDialog] = useState<DialogKind>(null); const [form, setForm] = useState(empty); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const open = (kind: DialogKind) => { setForm(empty); setDialog(kind); setMessage(''); setError(''); };
  const save = async () => { const config = dialog === 'material' ? { url: '/materials', body: { code: form.code, name: form.name, unit: form.unit, minimumStock: Number(form.minimumStock) } } : dialog === 'warehouse' ? { url: '/warehouses', body: { name: form.name, kind: form.kind } } : { url: '/users', body: { name: form.name, email: form.email, password: form.password, role: form.role } }; setSaving(true); setError(''); try { await http.post(config.url, config.body); await Promise.all(['admin-materials', 'admin-warehouses', 'users', 'materials', 'warehouses'].map((key) => queryClient.invalidateQueries({ queryKey: [key] }))); setMessage('Registro creado correctamente.'); setDialog(null); } catch (reason) { const response = (reason as { response?: { data?: { message?: string | string[] } } }).response?.data?.message; setError(Array.isArray(response) ? response.join('. ') : response ?? 'No fue posible guardar. Revisa tus permisos y los datos.'); } finally { setSaving(false); } };
  const toggle = async (kind: 'materials' | 'warehouses' | 'users', id: string, active: boolean) => { setError(''); try { const url = kind === 'users' ? `/users/${id}` : `/${kind}/${id}/active`; await http.patch(url, { active: !active }); await queryClient.invalidateQueries({ queryKey: [kind === 'materials' ? 'admin-materials' : kind === 'warehouses' ? 'admin-warehouses' : 'users'] }); setMessage(active ? 'Registro desactivado.' : 'Registro activado.'); } catch { setError('No fue posible cambiar el estado.'); } };
  const setPermission = async (item: Permission) => { setError(''); try { await http.patch('/permissions', { ...item, allowed: !item.allowed }); await queryClient.invalidateQueries({ queryKey: ['permissions'] }); setMessage('Permiso actualizado. Se aplicará en la siguiente operación.'); } catch { setError('No fue posible actualizar el permiso.'); } };
  return <Stack spacing={2.5}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h3" sx={{ fontSize: { xs: 34, sm: 46 } }}>Administración</Typography><Typography color="text.secondary" sx={{ mt: .6 }}>Catálogos operativos, ubicaciones y acceso por rol.</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="outlined" startIcon={<AddIcon />} onClick={() => open('material')}>Material</Button><Button variant="outlined" startIcon={<AddIcon />} onClick={() => open('warehouse')}>Almacén</Button><Button variant="contained" color="secondary" startIcon={<AddIcon />} onClick={() => open('user')}>Usuario</Button></Stack></Stack>
    {message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}
    <Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Materiales</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Código</TableCell><TableCell>Material</TableCell><TableCell>Unidad</TableCell><TableCell align="right">Mínimo</TableCell><TableCell /></TableRow></TableHead><TableBody>{(materials.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{item.code}</TableCell><TableCell>{item.name} {!item.active && <Chip size="small" label="Inactivo" sx={{ ml: 1 }} />}</TableCell><TableCell>{item.unit}</TableCell><TableCell align="right">{item.minimumStock}</TableCell><TableCell align="right"><Button size="small" onClick={() => toggle('materials', item.id, item.active)}>{item.active ? 'Desactivar' : 'Activar'}</Button></TableCell></TableRow>)}{!materials.data?.length && <TableRow><TableCell colSpan={5} align="center">Sin materiales registrados.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Box className="page-grid"><Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Almacenes y ubicaciones</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Nombre</TableCell><TableCell>Tipo</TableCell><TableCell /></TableRow></TableHead><TableBody>{(warehouses.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{item.name} {!item.active && <Chip size="small" label="Inactivo" sx={{ ml: 1 }} />}</TableCell><TableCell>{item.kind}</TableCell><TableCell align="right"><Button size="small" onClick={() => toggle('warehouses', item.id, item.active)}>{item.active ? 'Desactivar' : 'Activar'}</Button></TableCell></TableRow>)}{!warehouses.data?.length && <TableRow><TableCell colSpan={3} align="center">Sin ubicaciones registradas.</TableCell></TableRow>}</TableBody></Table></Paper>
      <Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Usuarios y roles</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Usuario</TableCell><TableCell>Rol</TableCell><TableCell /></TableRow></TableHead><TableBody>{(users.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{item.name}<Typography variant="caption" display="block" color="text.secondary">{item.email}</Typography>{!item.active && <Chip size="small" label="Inactivo" />}</TableCell><TableCell>{roleLabel(item.role)}</TableCell><TableCell align="right"><Button size="small" onClick={() => toggle('users', item.id, item.active)}>{item.active ? 'Desactivar' : 'Activar'}</Button></TableCell></TableRow>)}{!users.data?.length && <TableRow><TableCell colSpan={3} align="center">Sólo administradores pueden consultar usuarios.</TableCell></TableRow>}</TableBody></Table></Paper></Box>
    <Paper sx={{ overflow: 'auto' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Matriz de permisos por rol</Typography><Typography variant="body2" color="text.secondary">Los cambios se aplican en el API; administrador conserva el control de esta matriz.</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Permiso</TableCell>{roles.map((role) => <TableCell key={role} align="center">{roleLabel(role)}</TableCell>)}</TableRow></TableHead><TableBody>{[...new Set((permissions.data ?? []).map((item) => item.permission))].map((permission) => <TableRow key={permission}><TableCell>{permissionLabel(permission)}</TableCell>{roles.map((role) => { const item = permissions.data?.find((entry) => entry.permission === permission && entry.role === role); return <TableCell key={role} align="center"><Checkbox size="small" checked={item?.allowed ?? false} disabled={!item || (role === 'ADMIN' && permission === 'REPORT_APPROVE')} onChange={() => item && setPermission(item)} inputProps={{ 'aria-label': `${permissionLabel(permission)} para ${roleLabel(role)}` }} /></TableCell>; })}</TableRow>)}</TableBody></Table></Paper>
    <Dialog open={Boolean(dialog)} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>{dialog === 'material' ? 'Nuevo material' : dialog === 'warehouse' ? 'Nueva ubicación' : 'Nuevo usuario'}</DialogTitle><DialogContent><AdminForm kind={dialog} form={form} setForm={setForm} /></DialogContent><DialogActions><Button onClick={() => setDialog(null)}>Cancelar</Button><Button variant="contained" color="secondary" disabled={saving} onClick={save}>{saving ? 'Guardando…' : 'Guardar'}</Button></DialogActions></Dialog>
  </Stack>;
}
function AdminForm({ kind, form, setForm }: { kind: DialogKind; form: typeof empty; setForm: (value: typeof empty) => void }) { const set = (name: keyof typeof empty, value: string) => setForm({ ...form, [name]: value }); return <Stack spacing={2} sx={{ pt: 1 }}>{kind === 'material' && <><TextField label="Código" value={form.code} onChange={(event) => set('code', event.target.value)} required /><TextField label="Nombre" value={form.name} onChange={(event) => set('name', event.target.value)} required /><TextField label="Unidad" value={form.unit} onChange={(event) => set('unit', event.target.value)} required /><TextField label="Stock mínimo" type="number" value={form.minimumStock} onChange={(event) => set('minimumStock', event.target.value)} inputProps={{ min: 0 }} /></>}{kind === 'warehouse' && <><TextField label="Nombre" value={form.name} onChange={(event) => set('name', event.target.value)} required /><TextField select label="Tipo" value={form.kind} onChange={(event) => set('kind', event.target.value)}>{warehouseKinds.map((item) => <MenuItem key={item} value={item}>{item}</MenuItem>)}</TextField></>}{kind === 'user' && <><TextField label="Nombre" value={form.name} onChange={(event) => set('name', event.target.value)} required /><TextField label="Correo" type="email" value={form.email} onChange={(event) => set('email', event.target.value)} required /><TextField label="Contraseña temporal" type="password" value={form.password} onChange={(event) => set('password', event.target.value)} helperText="Mínimo 8 caracteres." required /><TextField select label="Rol" value={form.role} onChange={(event) => set('role', event.target.value)}>{roles.map((item) => <MenuItem key={item} value={item}>{roleLabel(item)}</MenuItem>)}</TextField></>}</Stack>; }
