import { useMemo, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import { downloadCsv, http, uploadLocalEvidence } from '../../api/http';

type Project = { id: string; name: string; location?: string; status: string; platforms: Platform[] };
type Platform = { id: string; name: string; location?: string; status: string; progress: string; projectId: string; activities: Activity[] };
type Activity = { id: string; name: string; progress: string; status: string; squareMeters?: string; cubicMeters?: string; trips: number; notes?: string; pendingItems?: string[]; photoPaths?: string[] };
type Material = { id: string; name: string; unit: string };
type Estimate = { id: string; quantity: string; threshold?: string; platform: { id: string; name: string; project: { name: string } }; activity?: { id: string; name: string } | null; material: Material };
type Comparison = { id: string; platform: { id: string; name: string; project: { name: string } }; activity?: { id: string; name: string } | null; material: Material; estimated: string; actual: string; variance: string; threshold: string; exceeded: boolean };
type DialogKind = 'project' | 'platform' | 'activity' | 'editActivity' | 'estimate' | null;

const emptyState = { name: '', location: '', status: 'PENDING', projectId: '', platformId: '', activityId: '', materialId: '', quantity: '', threshold: '15', progress: '', squareMeters: '', cubicMeters: '', trips: '0', notes: '', pendingItems: '' };
const projectStatus = [{ value: 'PENDING', label: 'Pendiente' }, { value: 'IN_PROGRESS', label: 'En proceso' }, { value: 'PAUSED', label: 'Pausado' }, { value: 'FINISHED', label: 'Terminado' }];
function statusLabel(status: string) { return projectStatus.find((item) => item.value === status)?.label ?? status; }

export function ControlPage() {
  const queryClient = useQueryClient();
  const projects = useQuery({ queryKey: ['projects'], queryFn: async () => (await http.get<Project[]>('/projects')).data, retry: false });
  const platforms = useQuery({ queryKey: ['platforms'], queryFn: async () => (await http.get<Platform[]>('/platforms')).data, retry: false });
  const materials = useQuery({ queryKey: ['materials'], queryFn: async () => (await http.get<Material[]>('/materials')).data, retry: false });
  const estimates = useQuery({ queryKey: ['estimates'], queryFn: async () => (await http.get<Estimate[]>('/estimates')).data, retry: false });
  const comparisons = useQuery({ queryKey: ['estimate-comparison'], queryFn: async () => (await http.get<Comparison[]>('/estimates/comparison')).data, retry: false });
  const [dialog, setDialog] = useState<DialogKind>(null); const [form, setForm] = useState(emptyState); const [editingActivity, setEditingActivity] = useState<Activity | null>(null); const [evidence, setEvidence] = useState<File | null>(null); const [selectedPlatform, setSelectedPlatform] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const platformList = platforms.data ?? [];
  const activePlatform = platformList.find((item) => item.id === selectedPlatform) ?? platformList[0];
  const activeActivities = activePlatform?.activities ?? [];
  const open = (kind: DialogKind) => { setForm({ ...emptyState, platformId: activePlatform?.id ?? '', projectId: projects.data?.[0]?.id ?? '' }); setEvidence(null); setDialog(kind); setMessage(''); setError(''); };
  const editActivity = (activity: Activity) => { setEditingActivity(activity); setForm({ ...emptyState, platformId: activePlatform.id, activityId: activity.id, name: activity.name, status: activity.status, progress: activity.progress, squareMeters: activity.squareMeters ?? '', cubicMeters: activity.cubicMeters ?? '', trips: String(activity.trips), notes: activity.notes ?? '', pendingItems: activity.pendingItems?.join(', ') ?? '' }); setEvidence(null); setDialog('editActivity'); setMessage(''); setError(''); };
  const save = async () => {
    setSaving(true); setError('');
    try {
    const uploadedPhoto = (dialog === 'activity' || dialog === 'editActivity') && evidence ? await uploadLocalEvidence(evidence) : undefined;
    const photoPaths = uploadedPhoto ? [...(editingActivity?.photoPaths ?? []), uploadedPhoto] : editingActivity?.photoPaths;
    const config = dialog === 'project' ? { url: '/projects', body: { name: form.name, location: form.location || undefined, status: form.status } }
      : dialog === 'platform' ? { url: '/platforms', body: { projectId: form.projectId, name: form.name, location: form.location || undefined } }
      : dialog === 'activity' || dialog === 'editActivity' ? { url: dialog === 'editActivity' ? `/activities/${form.activityId}` : '/activities', body: { ...(dialog === 'activity' ? { platformId: form.platformId } : {}), name: form.name, status: form.status, progress: form.progress ? Number(form.progress) : 0, squareMeters: form.squareMeters ? Number(form.squareMeters) : undefined, cubicMeters: form.cubicMeters ? Number(form.cubicMeters) : undefined, trips: Number(form.trips || 0), notes: form.notes || undefined, pendingItems: form.pendingItems.split(',').map((item) => item.trim()).filter(Boolean), photoPaths } }
      : { url: '/estimates', body: { platformId: form.platformId, activityId: form.activityId || undefined, materialId: form.materialId, quantity: Number(form.quantity), threshold: form.threshold ? Number(form.threshold) : undefined } };
    if (dialog === 'editActivity') await http.patch(config.url, config.body); else await http.post(config.url, config.body); await Promise.all(['projects', 'platforms', 'estimates', 'estimate-comparison', 'dashboard'].map((key) => queryClient.invalidateQueries({ queryKey: [key] }))); setMessage(dialog === 'estimate' ? 'Estimado guardado; el API aplicará el umbral configurado.' : 'Registro guardado correctamente.'); setDialog(null); setEditingActivity(null); }
    catch (reason) { const apiMessage = (reason as { response?: { data?: { message?: string | string[] } } }).response?.data?.message; setError(Array.isArray(apiMessage) ? apiMessage.join('. ') : apiMessage ?? 'No fue posible guardar. Revisa los campos y tus permisos.'); }
    finally { setSaving(false); }
  };
  return <Stack spacing={2.5}>
    <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={2}><Box><Typography variant="h3" sx={{ fontSize: { xs: 34, sm: 46 } }}>Control de obra</Typography><Typography color="text.secondary" sx={{ mt: .6 }}>Organiza proyectos, plataformas, actividades y consumo estimado.</Typography></Box><Stack direction="row" gap={1} flexWrap="wrap"><Button variant="outlined" startIcon={<AddIcon />} onClick={() => open('project')}>Proyecto</Button><Button variant="contained" color="secondary" startIcon={<AddIcon />} onClick={() => open('platform')}>Plataforma</Button></Stack></Stack>
    {message && <Alert severity="success">{message}</Alert>}{error && <Alert severity="error">{error}</Alert>}
    <Box className="page-grid"><Paper sx={{ overflow: 'hidden' }}><Box sx={{ p: 2.5, pb: 1 }}><Typography variant="h6">Proyectos y plataformas</Typography></Box><Table className="data-table"><TableHead><TableRow><TableCell>Proyecto</TableCell><TableCell>Ubicación</TableCell><TableCell>Estado</TableCell><TableCell align="right">Plataformas</TableCell></TableRow></TableHead><TableBody>{(projects.data ?? []).map((project) => <TableRow key={project.id}><TableCell>{project.name}</TableCell><TableCell>{project.location ?? '—'}</TableCell><TableCell><Chip size="small" label={statusLabel(project.status)} /></TableCell><TableCell align="right">{project.platforms.length}</TableCell></TableRow>)}{!projects.data?.length && <TableRow><TableCell colSpan={4} align="center">Aún no hay proyectos.</TableCell></TableRow>}</TableBody></Table></Paper>
      <Paper sx={{ p: 2.5 }}><Typography variant="h6">Acciones rápidas</Typography><Typography color="text.secondary" variant="body2" sx={{ mt: .6, mb: 2 }}>Registra el avance operativo y define el consumo esperado por material.</Typography><Stack spacing={1}><Button variant="outlined" disabled={!platformList.length} onClick={() => open('activity')}>Nueva actividad</Button><Button variant="outlined" disabled={!platformList.length || !(materials.data?.length)} onClick={() => open('estimate')}>Definir estimado</Button></Stack></Paper></Box>
    <Paper sx={{ p: { xs: 2, sm: 2.5 } }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} gap={1.5} sx={{ mb: 2 }}><Box><Typography variant="h6">Actividades por plataforma</Typography><Typography color="text.secondary" variant="body2">El avance admite porcentajes, m², m³, viajes, pendientes y evidencia.</Typography></Box><TextField select size="small" label="Plataforma" value={activePlatform?.id ?? ''} onChange={(event) => setSelectedPlatform(event.target.value)} sx={{ minWidth: { sm: 260 } }}><MenuItem value="" disabled>Selecciona una plataforma</MenuItem>{platformList.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField></Stack><Table className="data-table"><TableHead><TableRow><TableCell>Actividad</TableCell><TableCell>Avance</TableCell><TableCell>m² / m³</TableCell><TableCell>Estado</TableCell><TableCell>Pendientes</TableCell><TableCell align="right">Viajes</TableCell><TableCell /></TableRow></TableHead><TableBody>{activeActivities.map((item) => <TableRow key={item.id}><TableCell>{item.name}</TableCell><TableCell>{item.progress}%</TableCell><TableCell>{item.squareMeters ?? '—'} / {item.cubicMeters ?? '—'}</TableCell><TableCell>{statusLabel(item.status)}</TableCell><TableCell>{item.pendingItems?.length ?? 0}</TableCell><TableCell align="right">{item.trips}</TableCell><TableCell align="right"><Button size="small" onClick={() => editActivity(item)}>Actualizar</Button></TableCell></TableRow>)}{!activeActivities.length && <TableRow><TableCell colSpan={7} align="center">Sin actividades para esta plataforma.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Paper sx={{ overflow: 'hidden' }}><Stack direction="row" justifyContent="space-between" alignItems="center" gap={2} sx={{ p: 2.5, pb: 1 }}><Box><Typography variant="h6">Estimado vs. real</Typography><Typography color="text.secondary" variant="body2">El consumo se calcula desde salidas publicadas; umbral inicial configurable: 15%.</Typography></Box><Button variant="outlined" onClick={() => downloadCsv('/exports/comparisons.csv', 'estimado-real.csv')}>Exportar CSV</Button></Stack><Table className="data-table"><TableHead><TableRow><TableCell>Proyecto / plataforma</TableCell><TableCell>Material</TableCell><TableCell>Actividad</TableCell><TableCell align="right">Estimado</TableCell><TableCell align="right">Real</TableCell><TableCell align="right">Variación</TableCell></TableRow></TableHead><TableBody>{(comparisons.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{item.platform.project.name} · {item.platform.name}</TableCell><TableCell>{item.material.name}</TableCell><TableCell>{item.activity?.name ?? 'General'}</TableCell><TableCell align="right">{item.estimated} {item.material.unit}</TableCell><TableCell align="right">{item.actual} {item.material.unit}</TableCell><TableCell align="right" sx={{ color: item.exceeded ? 'secondary.main' : undefined, fontWeight: item.exceeded ? 700 : undefined }}>{item.variance}%</TableCell></TableRow>)}{!comparisons.data?.length && <TableRow><TableCell colSpan={6} align="center">Aún no hay estimados definidos.</TableCell></TableRow>}</TableBody></Table></Paper>
    <Dialog open={Boolean(dialog)} onClose={() => setDialog(null)} fullWidth maxWidth="sm"><DialogTitle>{dialog === 'project' ? 'Nuevo proyecto' : dialog === 'platform' ? 'Nueva plataforma' : dialog === 'activity' ? 'Nueva actividad' : dialog === 'editActivity' ? 'Actualizar actividad' : 'Definir estimado de material'}</DialogTitle><DialogContent><ControlForm kind={dialog} form={form} setForm={setForm} projects={projects.data ?? []} platforms={platformList} activities={activeActivities} materials={materials.data ?? []} />{(dialog === 'activity' || dialog === 'editActivity') && <Stack direction="row" alignItems="center" spacing={1} sx={{ mt: 2 }}><Button component="label" variant="outlined">Adjuntar foto<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setEvidence(event.target.files?.[0] ?? null)} /></Button><Typography variant="body2" color="text.secondary">{evidence?.name ?? `${editingActivity?.photoPaths?.length ?? 0} evidencia(s) existente(s)`}</Typography></Stack>}</DialogContent><DialogActions><Button onClick={() => setDialog(null)}>Cancelar</Button><Button variant="contained" color="secondary" onClick={save} disabled={saving}>{saving ? 'Guardando…' : 'Guardar'}</Button></DialogActions></Dialog>
  </Stack>;
}

function ControlForm({ kind, form, setForm, projects, platforms, activities, materials }: { kind: DialogKind; form: typeof emptyState; setForm: (value: typeof emptyState) => void; projects: Project[]; platforms: Platform[]; activities: Activity[]; materials: Material[] }) {
  const change = (name: keyof typeof emptyState, value: string) => setForm({ ...form, [name]: value }); const fields = <Stack spacing={2} sx={{ pt: 1 }}>
    {kind === 'project' && <><TextField label="Nombre" value={form.name} onChange={(event) => change('name', event.target.value)} required /><TextField label="Ubicación" value={form.location} onChange={(event) => change('location', event.target.value)} /><TextField select label="Estado" value={form.status} onChange={(event) => change('status', event.target.value)}>{projectStatus.map((item) => <MenuItem key={item.value} value={item.value}>{item.label}</MenuItem>)}</TextField></>}
    {kind === 'platform' && <><TextField select label="Proyecto" value={form.projectId} onChange={(event) => change('projectId', event.target.value)} required>{projects.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><TextField label="Nombre de plataforma" value={form.name} onChange={(event) => change('name', event.target.value)} required /><TextField label="Ubicación" value={form.location} onChange={(event) => change('location', event.target.value)} /></>}
    {(kind === 'activity' || kind === 'editActivity') && <>{kind === 'activity' && <TextField select label="Plataforma" value={form.platformId} onChange={(event) => change('platformId', event.target.value)} required>{platforms.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField>}<TextField label="Actividad" value={form.name} onChange={(event) => change('name', event.target.value)} required /><TextField select label="Estado" value={form.status} onChange={(event) => change('status', event.target.value)}>{projectStatus.map((item) => <MenuItem key={item.value} value={item.value}>{item.label}</MenuItem>)}</TextField><TextField label="Avance (%)" type="number" value={form.progress} onChange={(event) => change('progress', event.target.value)} inputProps={{ min: 0, max: 100 }} /><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><TextField fullWidth label="m²" type="number" value={form.squareMeters} onChange={(event) => change('squareMeters', event.target.value)} /><TextField fullWidth label="m³" type="number" value={form.cubicMeters} onChange={(event) => change('cubicMeters', event.target.value)} /><TextField fullWidth label="Viajes" type="number" value={form.trips} onChange={(event) => change('trips', event.target.value)} inputProps={{ min: 0 }} /></Stack><TextField label="Pendientes" value={form.pendingItems} onChange={(event) => change('pendingItems', event.target.value)} helperText="Separa los pendientes con comas." /><TextField label="Observaciones" value={form.notes} onChange={(event) => change('notes', event.target.value)} multiline minRows={2} /></>}
    {kind === 'estimate' && <><TextField select label="Plataforma" value={form.platformId} onChange={(event) => change('platformId', event.target.value)} required>{platforms.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><TextField select label="Actividad (opcional)" value={form.activityId} onChange={(event) => change('activityId', event.target.value)}><MenuItem value="">General de plataforma</MenuItem>{activities.map((item) => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField><TextField select label="Material" value={form.materialId} onChange={(event) => change('materialId', event.target.value)} required>{materials.map((item) => <MenuItem key={item.id} value={item.id}>{item.name} ({item.unit})</MenuItem>)}</TextField><TextField label="Cantidad estimada" type="number" value={form.quantity} onChange={(event) => change('quantity', event.target.value)} inputProps={{ min: 0, step: 0.001 }} required /><TextField label="Umbral de variación (%)" type="number" value={form.threshold} onChange={(event) => change('threshold', event.target.value)} inputProps={{ min: 0, max: 100 }} /></>}
  </Stack>; return fields;
}
