import React from 'react';
import ReactDOM from 'react-dom/client';
import { CssBaseline, ThemeProvider } from '@mui/material';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import { App } from './app/App';
import { NotificationsProvider } from './app/notifications';
import { theme } from './app/theme';
import './app/styles.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><ThemeProvider theme={theme}><CssBaseline /><QueryClientProvider client={new QueryClient()}><NotificationsProvider><BrowserRouter future={{ v7_startTransition: true, v7_relativeSplatPath: true }}><App /></BrowserRouter></NotificationsProvider></QueryClientProvider></ThemeProvider></React.StrictMode>);
